version: '3.5'
services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbt"
    ports:
      - "5432:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: yourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/root/.virtualenvs/dbt/bin/nosetests"
    env_file:
      - ./test.env
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - database

networks:
  default:
    name: dbt-net
